version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:woosekim
    container_name: nginx
    restart: always
    env_file:
      - .env
    networks:
      - inception-net
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:woosekim
    container_name: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - inception-net
    ports:
      - "9000"
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:woosekim
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception-net
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql

networks:
  inception-net:
    name: inception-net
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH_DB}
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH_WP}
